config/routes.rb
Rails.application.routes.draw do

   root 'client#index'
   get 'register_server' => 'client#register_server'
   get 'register' => 'client#register'
   get 'angemeldet' => 'client#sign_in'
   post 'angemeldet' => 'client#sign_in'
   get 'nachricht_schicken' => 'client#nachricht_schicken'
   get 'nachricht_abholen' => 'client#nachricht_abholen'
   get 'nachrichten_abholen' => 'client#nachrichten_abholen'
   get 'destroy_single' => 'client#destroy_single'
   get 'destroy_all' => 'client#destroy_all'
   get 'destroy_user' => 'client#destroy_user'
   get 'logout' => 'client#logout'

end

app/models/client.rb
class Client

  # Pubkey des Empfängers vom Server beziehen
  def self.get_pubkey(recipient)

    return RestClient.get(Constant.wsurl+recipient+'/pubkey')


  end

  # Masterkey bilden
  def self.generate_master_key(pass, salt)
    # Iterationen
    iter = 10000

    # Algorithmus
    digest = OpenSSL::Digest::SHA256.new

    # Key Länge
    len = 32

    # Fertiger Masterkey
    return OpenSSL::PKCS5.pbkdf2_hmac(pass, salt, iter, len, digest)

  end

  # Einzelne Nachricht löschen
  def self.destroy_single(recipient, id, timestamp, dig_sig)

    RestClient.delete(Constant.wsurl+recipient+'/message/'+id, {params: {login: recipient, timestamp: timestamp, digitale_signatur: dig_sig}})


  end

  # Alle Nachrichten löschen
  def self.destroy_all(recipient, timestamp, dig_sig)

    RestClient.delete(Constant.wsurl+recipient+'/messages/', {params: {login: recipient, timestamp: timestamp, digitale_signatur: dig_sig}})


  end

  def self.destroy_user(recipient, timestamp, dig_sig)

    RestClient.delete(Constant.wsurl+recipient, {params: {login: recipient, timestamp: timestamp, digitale_signatur: dig_sig}})


  end


  def self.dig_sig(timestamp, login)


    privkey_user = OpenSSL::PKey::RSA.new(Rails.cache.read('priv_key'))
    digest = OpenSSL::Digest::SHA256.new
    dig_sig = timestamp.to_s+login

    return Base64.encode64(privkey_user.sign digest, dig_sig)


  end
end

app/controllers/client_controller.rb
class ClientController < ApplicationController

  def register_server

    # Random 64 Byte Salt
    salt_masterkey = SecureRandom.random_bytes(64)

    # Fertiger Masterkey durch Aufruf der Methode generate_master_key in client.rb -> DRY
    masterkey = Client.generate_master_key(params[:pass], salt_masterkey)

    # Erzeuge RSA keys
    rsa_key = OpenSSL::PKey::RSA.new 2048


    # Pubkey auslesen
    pubkey_user = rsa_key.public_key

    # Verschlüsselung vorbereiten
    cipher = OpenSSL::Cipher.new 'AES-128-ECB'
    cipher.encrypt
    cipher.key = masterkey

    # Verschlüsseln
    encrypted = cipher.update(rsa_key.to_pem) + cipher.final

    # In Base64 zum persistieren in der DB encodieren
    privkey_user_enc = Base64.encode64(encrypted)
    salt_mk_64 = Base64.encode64(salt_masterkey)

    # Post request an den Server, WSURL als konstante URL des WebService in selbst definierter constants.rb
    RestClient.post(Constant.wsurl+params[:login], {salt_masterkey: salt_mk_64, pubkey_user: pubkey_user, privkey_user_enc: privkey_user_enc}) { |response|
      case response.code
        when 400
          flash[:alert] = 'Login bereits vergeben.'
        when 201
          flash[:notice] = 'Erfolgreich registriert.'
        else
          flash[:alert] = 'Irgendetwas ist schief gelaufen.'
      end
      redirect_to root_url
    }
  end

  def sign_in

    RestClient.get(Constant.wsurl+params[:login]) { |response|
      case response.code
        when 400
          flash[:alert] = 'Username nicht gefunden.'
          render :'client/index'
        when 200
          begin

            key = JSON.parse(response, symbolize_names: true)

            # Fertiger Masterkey durch Aufruf der Methode generate_master_key in client.rb -> DRY
            masterkey = Client.generate_master_key(params[:pass], Base64.decode64(key[:salt_masterkey]))



            # Entschlüsselung vorbereiten
            decipher = OpenSSL::Cipher.new 'AES-128-ECB'
            decipher.decrypt
            decipher.key = masterkey

            # Da in der DB in Base64 persistiert wieder decodieren
            privkey_user_enc = Base64.decode64(key[:privkey_user_enc])


            # Entschlüsseln
            privkey_user = decipher.update(privkey_user_enc) + decipher.final

            Rails.cache.write('login', params[:login], timeToLive: 600.seconds)
            Rails.cache.write('priv_key', privkey_user, timeToLive: 600.seconds)


            render :'client/angemeldet'
          rescue
            Rails.cache.delete('login')
            Rails.cache.delete('priv_key')
            flash[:alert] = 'Falsches Passwort'
            render :'client/index'
          end
        else
          Rails.cache.delete('login')
          Rails.cache.delete('priv_key')
          flash[:alert] = 'Irgendetwas ist falsch gelaufen.'
          render :'client/index'
      end
    }

  end

  def nachricht_schicken

    begin
      pubkey_recipient = JSON.parse(Client.get_pubkey(params[:recipient]), symbolize_names: true)[:pubkey_user]


      key_recipient = SecureRandom.hex(16)
     # iv = SecureRandom.hex(16)
      iv = SecureRandom.random_bytes(16)


      cipher = OpenSSL::Cipher.new 'AES-128-CBC'
      cipher.encrypt
      cipher.key = key_recipient
      cipher.iv = iv

      content_enc = cipher.update(params[:msg]) + cipher.final

      privkey_user = OpenSSL::PKey::RSA.new(Rails.cache.read('priv_key'))

      pubkey = OpenSSL::PKey::RSA.new(pubkey_recipient)

      key_recipient_enc = pubkey.public_encrypt(key_recipient)

      content_enc64 = Base64.encode64(content_enc)

      key_recipient_enc64 = Base64.encode64(key_recipient_enc)

      digest = OpenSSL::Digest::SHA256.new

      hash_data = Rails.cache.read('login')+content_enc64+iv+key_recipient_enc64
      #hash_data = "Das wird nicht funktionieren"
      sig_recipient = privkey_user.sign digest, hash_data
      sig_recipient64 = Base64.encode64(sig_recipient)

      timestamp =  Time.now.to_i
      #timestamp = 10000

      hash_data2 = Rails.cache.read('login')+content_enc64+iv+key_recipient_enc64+sig_recipient64+timestamp.to_s+params[:recipient]
      sig_service = privkey_user.sign digest, hash_data2
      sig_service64 = Base64.encode64(sig_service)
      iv = Base64.encode64(iv)

    rescue
      flash[:alert] = 'User nicht gefunden'
      render :'client/angemeldet'
      return
    end

    RestClient.post(Constant.wsurl+params[:recipient]+'/message', {sender: Rails.cache.read('login'), content_enc: content_enc64, iv: iv,
                                                                   key_recipient_enc: key_recipient_enc64, sig_recipient: sig_recipient64 , timestamp: timestamp,
                                                                   recipient: params[:recipient], sig_service: sig_service64 }) { |response|
      case response.code
        when 400
          flash.now[:alert] = 'User nicht gefunden'
        when 201
          flash.now[:notice] = 'Erfolgreich verschickt'
        else
          flash.now[:alert] = 'Irgendwas ist schief gelaufen'
      end
    }
    render :'client/angemeldet'
  end

  def nachricht_abholen

    timestamp =  Time.now.to_i
    login = Rails.cache.read('login')
    digitale_signatur64 = Client.dig_sig(timestamp, login )

    @response = RestClient.get(Constant.wsurl+login+'/message', {:params => {login: login, timestamp: timestamp, digitale_signatur: digitale_signatur64 }})
    if @response != 'null'

    @response = JSON.parse(@response, symbolize_names: true)

    pub_key = JSON.parse(Client.get_pubkey(@response[:sender]), symbolize_names: true)

    pubkey_user = OpenSSL::PKey::RSA.new(pub_key[:pubkey_user])

    check = false

    begin

      digest = OpenSSL::Digest::SHA256.new

      hash_data = @response[:sender]+@response[:content_enc]+Base64.decode64(@response[:iv])+@response[:key_recipient_enc]
      bla = Base64.decode64(@response[:sig_recipient])

      check = pubkey_user.verify(digest, bla, hash_data)

    rescue

    end

    return render :file => "#{Rails.root}/public/404" unless check

    privkey_user = OpenSSL::PKey::RSA.new(Rails.cache.read('priv_key'))
    key_recipient = privkey_user.private_decrypt(Base64.decode64(@response[:key_recipient_enc]))


    cipher = OpenSSL::Cipher.new 'AES-128-CBC'
    cipher.decrypt
    cipher.key = key_recipient
    cipher.iv = Base64.decode64(@response[:iv])

    content = cipher.update(Base64.decode64(@response[:content_enc])) + cipher.final


    @response = [@response[:sender], content, @response[:id], @response[:created_at].to_time]

    end



    render :'client/angemeldet'
  end

  def nachrichten_abholen

    timestamp =  Time.now.to_i
    privkey_user = OpenSSL::PKey::RSA.new(Rails.cache.read('priv_key'))
    digest = OpenSSL::Digest::SHA256.new

    dig_sig = timestamp.to_s+Rails.cache.read('login')

    digitale_signatur = privkey_user.sign digest, dig_sig

    digitale_signatur64 = Base64.encode64(digitale_signatur)

    response = RestClient.get(Constant.wsurl+Rails.cache.read('login')+'/messages', {:params => {login: Rails.cache.read('login'), timestamp: timestamp, digitale_signatur: digitale_signatur64 }})
    ausgabe = []

    if response != 'null'

      response = JSON.parse(response, symbolize_names: true)

      response.each do |i|


      pub_key = JSON.parse(Client.get_pubkey(i[:sender]), symbolize_names: true)

      pubkey_user = OpenSSL::PKey::RSA.new(pub_key[:pubkey_user])

      check = false
      begin

     #   digest = OpenSSL::Digest::SHA256.new
     #   hash_data = i[:sender]+i[:content_enc]+i[:iv]+i[:key_recipient_enc]
     #   bla = Base64.decode64(i[:sig_recipient])
     #   check = pubkey_user.verify(digest, bla, hash_data)


        pubkey_user.public_decrypt(Base64.decode64(i[:sig_recipient]))
        check = true
      rescue
      end

      return head 404 unless check

      privkey_user = OpenSSL::PKey::RSA.new(Rails.cache.read('priv_key'))

      key_recipient = privkey_user.private_decrypt(Base64.decode64(i[:key_recipient_enc]))


      cipher = OpenSSL::Cipher.new 'AES-128-CBC'
      cipher.decrypt
      cipher.key = key_recipient
      cipher.iv = Base64.decode64(i[:iv])
      content = cipher.update(Base64.decode64(i[:content_enc])) + cipher.final

      ausgabe.push [i[:sender], content, i[:id], i[:created_at].to_time]
      end

      @responses = ausgabe


      end
    render :'client/angemeldet'
  end



  def destroy_single

    timestamp =  Time.now.to_i
    login = Rails.cache.read('login')
    digitale_signatur64 = Client.dig_sig(timestamp, login )

    Client.destroy_single(Rails.cache.read('login'), params[:id], timestamp, digitale_signatur64)

    render :'client/angemeldet'

  end

  def destroy_all

    timestamp =  Time.now.to_i
    login = Rails.cache.read('login')
    digitale_signatur64 = Client.dig_sig(timestamp, login )

    Client.destroy_all(login, timestamp, digitale_signatur64)

    render :'client/angemeldet'

  end

  def destroy_user

    timestamp =  Time.now.to_i
    login = Rails.cache.read('login')
    digitale_signatur64 = Client.dig_sig(timestamp, login )

    Client.destroy_user(Rails.cache.read('login'), timestamp, digitale_signatur64)

    Rails.cache.delete('login')
    Rails.cache.delete('priv_key')

    flash[:notice] = 'Account gelöscht'

    redirect_to root_url

  end

  def logout

    Rails.cache.delete('login')
    Rails.cache.delete('priv_key')

    flash[:notice] = 'Erfolgreich ausgelogt'

    redirect_to root_url

  end

end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/client/_keine_nachrichten.html.erb
<br>
<strong>Keine Nachrichten für dich vorhanden</strong>

app/views/client/_neue_nachrichten.html.erb
<br>
<div class="panel pcool" id="shadow">
  <div class="panel-heading chathead" id="chath">
      <div class="row" style="margin-left: 8px">
        Von: <%= i[0] %>
        <div style="float: right; margin-right: 10px">
          <%= link_to "", destroy_single_path(id: i[2]), method: :get, data: {confirm: "Willst du diese Nachricht wirklich löschen?"},
                      class: "fa fa-trash-o", style: "color:red" %></div>
      </div>
      <div class="row" style="margin-left: 8px">
        Verschickt am <%= i[3].strftime("%d.%m.%Y") %> um <%= i[3].strftime("%H:%M:%S") %>
      </div>
  </div>
  <div class="panel-body chat" id="chatt"><%= simple_format(i[1]) %></div>
</div>

app/views/client/angemeldet.html.erb
  <h2>Hallo <%= Rails.cache.read('login') %>! Wähle eine Funktion:</h2>
  <ul class="nav nav-tabs">
    <li class="active"><a href="#empfangen">Nachricht empfangen</a></li>
    <li><a href="#schreiben">Nachricht schreiben</a></li>
    <li><a href="#account">Account</a></li>
  </ul>

  <div class="tab-content">
    <div id="empfangen" class="tab-pane fade in active">
      <br>


      <div class="row">
        <div class="col-sm-4" id="black">

          <%= button_to 'Letzte Nachricht abholen', 'nachricht_abholen', method: 'get', data: {authenticity_token: false} %>

        </div>

        <div class="col-sm-4" id="black">

          <%= button_to 'Alle Nachrichten abholen', 'nachrichten_abholen', method: 'get', data: {authenticity_token: false} %>

        </div>

        <div class="col-sm-4" id="black">

          <%= button_to 'Alle Nachrichten löschen', 'destroy_all', method: 'get', data: {confirm: 'Wirklich alle Nachrichten vom Server löschen?', authenticity_token: false} %>

        </div>
      </div>




      <% if @response == 'null' %>

          <%= render partial: 'client/keine_nachrichten' %>

      <% else %>

          <% if @response != nil %>

              <%= render partial: 'client/neue_nachrichten', locals: {i: @response}%>

          <% end %>

          <% if @responses != nil %>

              <% @responses.each do |i| %>

                  <%= render partial: 'client/neue_nachrichten', locals: {i: i}  %>

              <% end %>

          <% end %>

          <% if @responses == [] %>

              <%= render partial: 'client/keine_nachrichten' %>

          <% end %>
      <% end %>

    </div>
    <div id="schreiben" class="tab-pane fade">
      <h3>Neue Nachricht</h3>
      <p><%= form_tag('/nachricht_schicken', method: 'get', class:'form-horizontal', authenticity_token: false) do %>

          <div class="form-group">
            <label class="control-label col-sm-1"><i class="fa fa-user" aria-hidden="true"></i></label>
            <div class="col-sm-4">
              <%= text_field_tag(:recipient, '', class: 'form-control', placeholder:'Empfänger') %>
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-sm-1"><i class="fa fa-envelope" aria-hidden="true"></i></label>
            <div class="col-sm-4">
              <%= text_area_tag(:msg, '', class: 'form-control', placeholder:'Nachricht', rows:'5', id:'comment', type:'textarea') %>
            </div>
          </div>

          <%= submit_tag('Abschicken', id:'black') %>

      <% end %>

    </div>

    <div id="account" class="tab-pane fade">
      <h3>Account löschen</h3>
    <div id="black">
      <%= button_to 'Account löschen', 'destroy_user', method: 'get', data: {confirm: 'Möchtest du wirklich deinen Account löschen? Alle erhaltenen Nachrichten gehen verloren!', authenticity_token: false} %>

    </div>



    </div>

  </div>



<script>
  $(document).ready(function(){
    $(".nav-tabs a").click(function(){
      $(this).tab('show');
    });
  });

</script>

app/views/client/index.html.erb
<div id="center">
    Willkommen bei KryptoChat, deinem sicheren Chat Tool im Internet.
  <br>
  <a href="#" data-toggle="modal" data-target="#login-modal" style="color:cornflowerblue">Log dich ein</a> um zu starten, oder melde dich
  <a href="#" data-toggle="modal" data-target="#register-modal" style="color:cornflowerblue">hier</a> an, um unseren Service kostenlos zu nutzen.
<br><br><br><br>

  <div class="container" style="max-width: 75%">
    <h2>Unsere Features:</h2>
    <div class="list-group">
      <a href="#" class="list-group-item">
        <h2 class="list-group-item-heading" style="margin-left: 45px"><i class="fa fa-user-secret" aria-hidden="true"></i> <strong>Sichere Passwörter</strong></h2>
        <p class="list-group-item-text">Unser Service speichert zu keinem Zeitpunkt dein Passwort.</p>
      </a>
      <a href="#" class="list-group-item">
        <h2 class="list-group-item-heading" style="margin-left: 10px"><i class="fa fa-user-secret" aria-hidden="true"></i> <strong>Verschlüsselung</strong></h2>
        <p class="list-group-item-text">Wir verwenden sowohl symmetrische, als auch asymmetrische Verschlüsselungsverfahren.</p>
      </a>
      <a href="#" class="list-group-item">
        <h2 class="list-group-item-heading" style="margin-left: 10px"><i class="fa fa-user-secret" aria-hidden="true"></i> <strong>Authentifizierung</strong></h2>
        <p class="list-group-item-text">Unser Service verwendet eine Vielzahl von Machanismen, um sicher zu stellen, dass niemand in deinem Namen Nachrichten versenden kann.</p>
      </a>
    </div>
  </div>
</div>

app/views/client/nachricht_abholen.js.erb
$('#div_id').html("<%= render :partial => 'keine_nachrichten' %>");

app/views/client/register.html.erb
<div id="center">
  Registriere dich für unseren Service <br><br>

  <%= form_tag('/register_server', method: 'post', class:'form-horizontal', authenticity_token: false) do %>

      <div class="form-group">
        <label class="control-label col-sm-4"><i class="fa fa-user" aria-hidden="true"></i></label>
        <div class="col-sm-4">
          <%= text_field_tag(:login, '', class: 'form-control', placeholder:'Dein Username', id:'usr', type:'username') %>
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-sm-4"><i class="fa fa-key" aria-hidden="true"></i></label>
        <div class="col-sm-4">
          <%= text_field_tag(:pass, '', class: 'form-control', placeholder:'Dein Passwort', id:'pwd', type:'password') %>
        </div>
      </div>

      <%= submit_tag('Registrieren', id:'black') %>

  <% end %>

  <%= link_to 'Zurück', root_path, id:'black' %>

</div>