config/routes.rb
Rails.application.routes.draw do

   root 'client#index'
   get 'register_server' => 'client#register_server'
   get 'register' => 'client#register'
   get 'angemeldet' => 'client#sign_in'
   post 'angemeldet' => 'client#sign_in'
   get 'nachricht_schicken' => 'client#nachricht_schicken'
   get 'nachricht_abholen' => 'client#nachricht_abholen'
   get 'nachrichten_abholen' => 'client#nachrichten_abholen'
   get 'destroy_single' => 'client#destroy_single'
   get 'destroy_all' => 'client#destroy_all'
   get 'destroy_user' => 'client#destroy_user'
   get 'logout' => 'client#logout'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KryptoChat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'matrix_icon.png' %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">KryptoChat</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <% if Rails.cache.read('login') == nil or Rails.cache.read('login') == '' %>

        <li><a href="#" data-toggle="modal" data-target="#login-modal"><i class="fa fa-sign-in" aria-hidden="true"></i> Login</a>

          <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
            <div class="modal-dialog">
              <div class="loginmodal-container">
                <h1>Melde dich an</h1><br>

                <%= form_tag('/angemeldet', method: 'post', class:'form-horizontal', authenticity_token: false) do %>

                    <div class="form-group">
                      <label class="control-label col-sm-2"><i class="fa fa-user" aria-hidden="true"></i></label>
                      <div class="col-sm-10">
                        <%= text_field_tag(:login, '', class: 'form-control', placeholder:'Dein Username') %>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="control-label col-sm-2"><i class="fa fa-key" aria-hidden="true"></i></label>
                      <div class="col-sm-10">
                        <%= text_field_tag(:pass, '' ,placeholder:'Dein Passwort', class: 'form-control', type:'password') %>
                      </div>
                    </div>

                    <%= submit_tag('Anmelden', id:'black', style:'width:60%; margin:auto') %>

                <% end %>

              </div>
            </div>
          </div>
        </li>

        <li>
          <a href="#" data-toggle="modal" data-target="#register-modal"><i class="fa fa-user-plus" aria-hidden="true"></i> Registrieren</a>
          <div class="modal fade" id="register-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
            <div class="modal-dialog">
              <div class="registermodal-container">
                <h1>Registriere dich für unseren Service</h1><br>

                <%= form_tag('/register_server', method: 'get', class:'form-horizontal', authenticity_token: false) do %>

                    <div class="form-group">
                      <label class="control-label col-sm-2"><i class="fa fa-user" aria-hidden="true"></i></label>
                      <div class="col-sm-10">
                        <%= text_field_tag(:login, '', class: 'form-control', placeholder:'Dein Username') %>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="control-label col-sm-2"><i class="fa fa-key" aria-hidden="true"></i></label>
                      <div class="col-sm-10">
                        <%= text_field_tag(:pass, '' ,placeholder:'Dein Passwort', class: 'form-control', type:'password') %>
                      </div>
                    </div>

                    <%= submit_tag('Registrieren', id:'black', style:'width:60%; margin:auto') %>

                <% end %>

              </div>
            </div>
          </div>

        </li>
            <% else %>

            <li>
              <%= link_to 'Ausloggen', logout_path %>
            </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid text-center">
  <div class="row content">
    <div class="col-sm-2 sidenav">
    </div>
    <div class="col-sm-8 text-left">

      <% if flash[:notice] %>
          <div class="alert alert-success" id="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
      <% end %>

      <% if flash[:alert] %>
          <div class="alert alert-danger" id="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
      <% end %>

        <%= yield %>



    </div>
    <div class="col-sm-2 sidenav">
    </div>
  </div>
</div>
</div>

<footer class="container-fluid text-center">
  <p><i class="fa fa-copyright" aria-hidden="true"></i> Copyright Team 10 Web Engineering</p>
</footer>

</body>
</html>